#!/bin/sh
echo -ne "`~/Code/my_ode/info_dist.pl $1 | tee temp | awk 'BEGIN{max=0; maxpos=0}{if ($2>max) {max=$2; maxpos=$1}}END{print maxpos " " max}'` "
echo -ne "`head -1 temp | awk '{print $2}'` "
test=`echo $1 | sed 's/^.*or_\([0-9]\.[0-9][0-9]\)_.*$/\1/g'`
~/Code/my_ode/analyse_ode_dat.pl $1 1 | awk '{oI=$2*'$test'; print oI " " '$test' " " $2}'
