#!/bin/sh

echo "set terminal gif; "\
     "set output '`dirname $1`/`basename $1 .dat`.gif';" \
     "set xlabel 'information generation';" \
     "set ylabel '# individuals';" \
     "set style fill solid 1.0;" \
     "set nokey;" \
     "set yrange [0:$2];" \
     "set title 'information distribution';" \
     "plot '$1' u 1:2 w boxes" | gnuplot
