#!/bin/sh

echo "set terminal postscript eps enhanced color dashed defaultplex 'Helvetica' 24;" \
     "set output '`basename $1 .dat`.eps';" \
     "set bmargin 1;" \
     "set tmargin 1;" \
     "set rmargin 1;" \
     "set lmargin 1;" \
     "set format '%3.1e';" \
     "set key right top samplen 2 spacing 1.5;" \
     "set style line 1 lt 1 lc rgb 'blue'  lw 2;" \
     "set style line 2 lt 2 lc rgb 'blue'  lw 3;" \
     "set style line 3 lt 1 lc rgb 'red'   lw 2;" \
     "set style line 4 lt 2 lc rgb 'red'   lw 3;" \
     "set style line 5 lt 1 lc rgb 'green' lw 2;" \
     "set style line 6 lt 2 lc rgb 'green' lw 3;" \
     "set xlabel 'time';" \
     "set ylabel '';" \
     "set title 'simulation';" \
     "plot '$1' u 1:2 ls 1 title 'S' w l," \
     "     '$1' u 1:3 ls 3 title 'I' w l," \
     "     '$1' u 1:4 ls 5 title 'R' w l," \
     "     '$1' u 1:(\$2-\$5) ls 2 title 'S-S''' w l," \
     "     '$1' u 1:(\$3-\$6) ls 4 title 'I-I''' w l," \
     "     '$1' u 1:(\$4-\$7) ls 6 title 'R-R''' w l" | gnuplot
