#!/bin/sh

echo "set terminal postscript eps enhanced color dashed defaultplex 'Helvetica' 24;" \
     "set output '`basename $1 .dat`.suminfo.eps';" \
     "set key right top samplen 2 spacing 1.5;" \
     "set style line 1 lt 1 lc rgb 'blue'  lw 2;" \
     "set style line 2 lt 2 lc rgb 'blue'  lw 3;" \
     "set style line 3 lt 1 lc rgb 'red'   lw 2;" \
     "set style line 4 lt 2 lc rgb 'red'   lw 3;" \
     "set style line 5 lt 1 lc rgb 'green' lw 2;" \
     "set style line 6 lt 2 lc rgb 'green' lw 3;" \
     "set style line 7 lt 2 lc rgb 'black' lw 3;" \
     "set xrange [0:];" \
     "set yrange [0:];" \
     "set xlabel 'time';" \
     "set ylabel '';" \
     "plot '$1' u 1:2 ls 1 title 'S' w l," \
     "     '$1' u 1:3 ls 3 title 'I' w l," \
     "     '$1' u 1:4 ls 5 title 'R' w l," \
     "     '$1' u 1:(("'$2+$3+$4'")-("'$5+$6+$7'")) ls 7 title 'Awareness' w l" | gnuplot
#     "set bmargin 1;" \
#     "set tmargin 1;" \
#     "set rmargin 1;" \
#     "set lmargin 1;" \
